#ifndef ELMAH_MODELS_HPP_
#define ELMAH_MODELS_HPP_

#include <DiFrancescoNoble1985.hpp>
#include <DiFrancescoNoble1985BackwardEuler.hpp>
#include <DiFrancescoNoble1985BackwardEulerNoLut.hpp>
#include <DiFrancescoNoble1985Cvode.hpp>
#include <DiFrancescoNoble1985CvodeOpt.hpp>
#include <DiFrancescoNoble1985Opt.hpp>
#include <FaberRudy2000.hpp>
#include <FaberRudy2000BackwardEuler.hpp>
#include <FaberRudy2000BackwardEulerNoLut.hpp>
#include <FaberRudy2000Cvode.hpp>
#include <FaberRudy2000CvodeOpt.hpp>
#include <FaberRudy2000Opt.hpp>
#include <FoxModel2002.hpp>
#include <FoxModel2002BackwardEuler.hpp>
#include <FoxModel2002BackwardEulerNoLut.hpp>
#include <FoxModel2002Cvode.hpp>
#include <FoxModel2002CvodeOpt.hpp>
#include <FoxModel2002Opt.hpp>
#include <HodgkinHuxley1952.hpp>
#include <HodgkinHuxley1952BackwardEuler.hpp>
#include <HodgkinHuxley1952BackwardEulerNoLut.hpp>
#include <HodgkinHuxley1952Cvode.hpp>
#include <HodgkinHuxley1952CvodeOpt.hpp>
#include <HodgkinHuxley1952Opt.hpp>
#include <LuoRudy1991.hpp>
#include <LuoRudy1991BackwardEuler.hpp>
#include <LuoRudy1991BackwardEulerNoLut.hpp>
#include <LuoRudy1991Cvode.hpp>
#include <LuoRudy1991CvodeOpt.hpp>
#include <LuoRudy1991Opt.hpp>
#include <Mahajan2008.hpp>
#include <Mahajan2008BackwardEuler.hpp>
#include <Mahajan2008BackwardEulerNoLut.hpp>
#include <Mahajan2008Cvode.hpp>
#include <Mahajan2008CvodeOpt.hpp>
#include <Mahajan2008Opt.hpp>
#include <Maleckar2008.hpp>
#include <Maleckar2008BackwardEuler.hpp>
#include <Maleckar2008BackwardEulerNoLut.hpp>
#include <Maleckar2008Cvode.hpp>
#include <Maleckar2008CvodeOpt.hpp>
#include <Maleckar2008Opt.hpp>
#include <NobleVargheseKohlNoble1998a.hpp>
#include <NobleVargheseKohlNoble1998aBackwardEuler.hpp>
#include <NobleVargheseKohlNoble1998aBackwardEulerNoLut.hpp>
#include <NobleVargheseKohlNoble1998aCvode.hpp>
#include <NobleVargheseKohlNoble1998aCvodeOpt.hpp>
#include <NobleVargheseKohlNoble1998aOpt.hpp>
#include <Shannon2004.hpp>
#include <Shannon2004BackwardEuler.hpp>
#include <Shannon2004BackwardEulerNoLut.hpp>
#include <Shannon2004Cvode.hpp>
#include <Shannon2004CvodeOpt.hpp>
#include <Shannon2004Opt.hpp>
#include <TenTusscher2006Epi.hpp>
#include <TenTusscher2006EpiBackwardEuler.hpp>
#include <TenTusscher2006EpiBackwardEulerNoLut.hpp>
#include <TenTusscher2006EpiCvode.hpp>
#include <TenTusscher2006EpiCvodeOpt.hpp>
#include <TenTusscher2006EpiOpt.hpp>


#endif // ELMAH_MODELS_HPP_